### PR TITLE
Change to Factory way

### PR DESCRIPTION
**Pull request by guilhermedecampo**
This PR intent to add:
- jshint linter
- readme update to factory style
- factory style on the code

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
Thanks for this. I usually lean more to `eslint`? do you think we could switch to this?

**Comment by abhiaiyer91** [comment]
Or we could remove it from this pr, and i can get `eslint` setup

**Comment by guilhermedecampo** [comment]
Ok I'll remove it. Thanks!

**Comment by abhiaiyer91** [comment]
Okay merging this! Should we publish a new version of the package?

**Comment by guilhermedecampo** [comment]
Yes please. But we should add no backward compatibility no?

**Comment by abhiaiyer91** [comment]
Yeah no ones using this at big scale yet, we can just stick with factory from here on out. Will release now.

**Pull request merged**
